name: Stacks
options:
  bundleIdPrefix: com.stacks
  deploymentTarget:
    iOS: "15.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

targets:
  Stacks:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Stacks/Stacks
        excludes:
          - "**/*.md"
    resources:
      - path: Stacks/Stacks/Assets.xcassets
      - path: assets
        buildPhase: copyFiles
        copyFiles:
          destination: resources
    info:
      path: Stacks/Stacks/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.stacks.app
        PRODUCT_NAME: Stacks
        SWIFT_VERSION: "5.9"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_FILE: Stacks/Stacks/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: $(inherited)
        ENABLE_PREVIEWS: YES
    scheme:
      environmentVariables:
        API_BASE_URL: http://localhost:8080
    coreData:
      currentVersion: StacksModel
      path: Stacks/Stacks/StacksModel.xcdatamodeld

